name: my_byaj_book
description: A loan management and financial tool application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  intl: ^0.18.1
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  flutter_contacts: ^1.1.9+2
  fl_chart: ^0.71.0
  pdf: ^3.11.3
  open_file: ^3.5.10
  path_provider: ^2.1.5
  timezone: ^0.10.0
  device_info_plus: ^11.4.0
  installed_apps: ^1.6.0
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/my_byaj_book_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/my_byaj_book_logo.png"

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/my_byaj_book_logo.png
