name: my_byaj_book
description: A loan management and financial tool application.
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  intl: ^0.17.0
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  flutter_contacts: ^1.1.9+2
  fl_chart: ^0.71.0
  pdf: ^3.11.3
  open_file: ^3.5.10
  path_provider: ^2.1.5
  timezone: ^0.10.1
  device_info_plus: ^11.4.0
  flutter_local_notifications: ^19.1.0
  cross_file: ^0.3.3+6
  timeago: ^3.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_auth: ^5.5.3
  firebase_app_check: ^0.3.2+5
  firebase_messaging: ^15.2.5

  uuid: any
  path: any
  flutter_timezone: ^4.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  sms_autofill: ^2.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/my_byaj_book_logo.png"
  adaptive_icon_background: "#0D47A1"
  adaptive_icon_foreground: "assets/my_byaj_book_logo.png"
  min_sdk_android: 23
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
  linux:
    generate: false

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/my_byaj_book_logo.png

flutter_native_splash:
  color: "#0D47A1"
  image: assets/native_splash_icon.png
  color_dark: "#0D47A1"
  image_dark: assets/native_splash_icon.png
  
  android_12:
    image: assets/native_splash_icon.png
    icon_background_color: "#0D47A1"
    image_dark: assets/native_splash_icon.png
    icon_background_color_dark: "#0D47A1"
  
  android: true
  ios: true
  web: false

  # Set scaling options to prevent stretching  
  android_gravity: center
  ios_content_mode: center
  
  # Keep splash on screen until app fully loads
  fullscreen: true
  
  # Ensure backward compatibility
  info_plist_files:
    - 'ios/Runner/Info.plist'